version: '3.4'

services:
    webapp:
        image: kodesonen-webapp
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
