# CI/CD Pipeline - Build dotnet project
name: build_project

on:
  pull_request:
    branches: [dev-server]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
  
    - name: Dotnet publish
      run: dotnet publish Kodesonen.sln -c Release -o build
