name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    # Build project
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: '3.1.x'
    #- run: dotnet build <my project>
  
    - name: Dotnet Publish
      run: dotnet publish WebApplication/Kodesonen.sln -c Release -o deploy
